name: Test changes

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y make
        python3 -m pip install --upgrade pip
        pip install setuptools wheel twine
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3
        # Remove this once this issue is no longer in preview: https://github.com/python-poetry/poetry/issues/2742
        source $HOME/.poetry/env
        poetry self update --preview
    - name: Audit
      run: |
        export PATH="$HOME/.poetry/bin:${PATH}"
        make audits

